project:
  type: book
  output-dir: docs

lang: uk-UA

book:
  title: "R для психологів"
  author: "Олександр Виноградов"
  date: "12/20/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

crossref:
  tbl-title: Таблиця
  fig-title: Рисунок

bibliography: references.bib

toc-title: "Зміст на сторінці"

format:
  html:
    theme:
      - darkly
      - brand

  pdf:
    documentclass: scrreprt
    mainfont: Arial
    sansfont: Arial
    monofont: Consolas

